openapi: 3.0.0
info:
  title: dumbp
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /directions:
    get:
      summary: Get directions
      tags: []
      responses: {}
      operationId: get-directions
      parameters:
        - schema:
            type: string
          in: query
          name: format
          description: Can be either `json` or `html`
    post:
      summary: Post directions data
      operationId: post-directions
      responses:
        '200':
          description: OK
components:
  schemas: {}
